services:
  - type: web
    name: paulayusun
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -- timeout 200
    build:
      pythonVersion: 3.12.6
      
